[tool.poetry]
name = "enphase-proxy"
version = "0.0.0"  # DO NOT CHANGE -- set during build
description = "Connect to your Enphase Envoy locally and proxy the API."
authors = ["Paul Lockaby <paul@paullockaby.com>"]
packages = [{include = "enphase_proxy", from = "src"}]

[tool.poetry.scripts]

[tool.poetry.dependencies]
python = "^3.11"
quart = "^0.18.4"
aiohttp = "^3.8.4"
tenacity = "^8.2.2"
hypercorn = {extras = ["uvloop"], version = "^0.14.3"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pre-commit = "^3.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
