[project]
name = "enphase-proxy"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.12 <3.13"

[tool.poetry]
name = "enphase-proxy"
version = "0.0.0"  # DO NOT CHANGE -- set during build
description = "Connect to your Enphase Envoy locally and proxy the API."
authors = ["Paul Lockaby <paul@paullockaby.com>"]
packages = [{include = "enphase_proxy", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12 <3.13"
quart = "^0.19.3"
aiohttp = "^3.8.6"
tenacity = "^9.0.0"
hypercorn = {extras = ["uvloop"], version = "^0.17.3"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pytest-cov = "^5.0.0"
pytest-mypy = "^0.10.3"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
